import type { PromptCondition, RunType, TaskRecord } from "@/types";
import type { TestModelId } from "@/lib/models/registry";

/**
 * 5b — Execution-layer pairing.
 *
 * "both" is the only scope that produces analysable data: the study is a
 * within-task paired comparison, so a task run under one condition alone
 * contributes nothing to it. Single-condition scopes remain reachable only
 * behind an explicit unpaired-data acknowledgement, which is off by default.
 */
export type ConditionScope = PromptCondition | "both";

export const PAIRED_SCOPE: ConditionScope = "both";

export function isUnpairedScope(scope: ConditionScope): boolean {
  return scope !== "both";
}

export type BatchJobStatus =
  | "pending"
  | "running"
  | "evaluating"
  | "done"
  | "failed"
  /** Never dispatched — the run was halted by the mid-batch callability check. */
  | "aborted"
  /**
   * Never dispatched — this cell was already generated by an earlier run.
   *
   * The main study is n=1, so its generation is not repeatable: /api/run
   * refuses a duplicate main cell. Re-running a partly-complete batch would
   * therefore produce one 409 per existing cell. Marking them lets a halted run
   * be resumed by starting a new batch, without re-spending generation tokens
   * and without a wall of spurious failures.
   *
   * NOTE: a skipped cell may still be missing evaluations. Resuming completes
   * the REMAINING generations; cells whose judging failed need a separate
   * evaluate-only pass.
   */
  | "skipped_existing";

export interface BatchJob {
  task_id: string;
  domain: TaskRecord["domain"];
  task_description: string;
  /**
   * The producing model. Part of the job rather than a page-level setting so a
   * single pass can cover both test models — see buildBatchJobs for why the
   * ordering matters.
   */
  model: TestModelId;
  condition: PromptCondition;
  status: BatchJobStatus;
  error?: string;
  total_score?: number;
}

/**
 * Pause the run once this many generations have been dispatched, for inspection
 * before committing the remaining calls.
 *
 * 100 is not arbitrary: under the task-major ordering below it is exactly 25
 * whole tasks — 50 complete pairs, 25 per model — so the pause can never land
 * mid-pair and the checkpoint sample is balanced across both models.
 */
export const CHECKPOINT_AFTER_GENERATIONS = 100;

/** Identifies one cell of the design, within a run_type. */
export function cellKey(r: {
  task_id: string;
  model_name: string;
  prompt_condition: PromptCondition;
}): string {
  return `${r.task_id}::${r.model_name}::${r.prompt_condition}`;
}

/**
 * Marks jobs whose cell already has a recorded generation of this run_type, so
 * a resumed batch dispatches only what is genuinely outstanding.
 */
export function markExistingCells(
  jobs: BatchJob[],
  existing: Array<{
    task_id: string;
    model_name: string;
    prompt_condition: PromptCondition;
    run_type: RunType;
  }>,
  runType: RunType
): BatchJob[] {
  const done = new Set(
    existing.filter((r) => r.run_type === runType).map((r) => cellKey(r))
  );
  return jobs.map((j) =>
    done.has(cellKey({ task_id: j.task_id, model_name: j.model, prompt_condition: j.condition }))
      ? { ...j, status: "skipped_existing" as const }
      : j
  );
}

export function isTaskReadyForScope(task: TaskRecord, scope: ConditionScope): boolean {
  if (scope === "baseline") return Boolean(task.baseline_prompt);
  if (scope === "craft") return Boolean(task.craft_prompt);
  return Boolean(task.baseline_prompt) && Boolean(task.craft_prompt);
}

/**
 * Job ordering is TASK-major, then model, then condition:
 *
 *   T001/claude/baseline, T001/claude/craft, T001/gpt/baseline, T001/gpt/craft,
 *   T002/claude/baseline, ...
 *
 * Two properties follow, and both matter:
 *
 * 1. Every task is finished completely before the next begins, so any prefix of
 *    the queue that is a multiple of 4 is a set of WHOLE pairs, balanced across
 *    models. A pause or a halt can never bisect a pair.
 *
 * 2. The two models are interleaved in wall-clock time rather than run in
 *    blocks. Under model-blocked ordering a degraded provider hour lands
 *    entirely on one model's data and shows up as a model effect; interleaved,
 *    it hits both roughly equally and stays noise.
 */
export function buildBatchJobs(
  tasks: TaskRecord[],
  selectedIds: Set<string>,
  scope: ConditionScope,
  models: readonly TestModelId[]
): BatchJob[] {
  const conditions: PromptCondition[] = scope === "both" ? ["baseline", "craft"] : [scope];
  const jobs: BatchJob[] = [];

  for (const task of tasks) {
    if (!selectedIds.has(task.task_id)) continue;
    for (const model of models) {
      for (const condition of conditions) {
        jobs.push({
          task_id: task.task_id,
          domain: task.domain,
          task_description: task.task_description,
          model,
          condition,
          status: "pending",
        });
      }
    }
  }

  return jobs;
}
